site_name: AI Evolution for Enterprise Developers
site_description: Practical, open-source focused guide from rule-based systems to GenAI
site_url: 
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Evolution: 01-evolution.md
  - Rule-Based: 02-rule-based.md
  - Classic ML: 03-classic-ml.md
  - Deep Learning: 04-deep-learning.md
  - Transformers: 05-transformers.md
  - Generative AI: 06-generative-ai.md
  - Tooling: 07-tooling.md
  - Evaluation & Guardrails: 08-evaluation-guardrails.md
  - Governance: 09-governance.md
  - Future: 10-future.md
  - Appendices:
    - Decision Trees: appendix-decision-trees.md
    - ROI Examples: appendix-roi-examples.md

